remote_theme: pages-themes/minimal

title: MLS
description: Messaging Layer Security (MLS) is an IETF working group building a modern, efficient, secure group messaging protocol.
show_downloads: false

plugins:
  - jekyll-remote-theme

# google_analytics: [Your Google Analytics tracking ID]
